export const initialMovies = [
  {
    Title: "The Shawshank Redemption",
    Year: "1994",
    Rated: "R",
    Released: "14 Oct 1994",
    Runtime: "142 min",
    Genre: "Drama",
    Director: "Frank Darabont",
    Writer: "Stephen King, Frank Darabont",
    Actors: "Tim Robbins, Morgan Freeman, Bob Gunton",
    Plot: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    Language: "English",
    Country: "United States",
    Awards: "Nominated for 7 Oscars. 21 wins & 43 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "9.3/10" },
      { Source: "Rotten Tomatoes", Value: "91%" },
      { Source: "Metacritic", Value: "81/100" },
    ],
    Metascore: "81",
    imdbRating: "9.3",
    imdbVotes: "2,651,602",
    imdbID: "tt0111161",
    Type: "movie",
    DVD: "21 Dec 1999",
    BoxOffice: "$28,767,189",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Godfather",
    Year: "1972",
    Rated: "R",
    Released: "24 Mar 1972",
    Runtime: "175 min",
    Genre: "Crime, Drama",
    Director: "Francis Ford Coppola",
    Writer: "Mario Puzo, Francis Ford Coppola",
    Actors: "Marlon Brando, Al Pacino, James Caan",
    Plot: "The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.",
    Language: "English, Italian, Latin",
    Country: "United States",
    Awards: "Won 3 Oscars. 32 wins & 30 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "9.2/10" },
      { Source: "Rotten Tomatoes", Value: "97%" },
      { Source: "Metacritic", Value: "100/100" },
    ],
    Metascore: "100",
    imdbRating: "9.2",
    imdbVotes: "1,840,332",
    imdbID: "tt0068646",
    Type: "movie",
    DVD: "11 May 2004",
    BoxOffice: "$136,381,073",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Dark Knight",
    Year: "2008",
    Rated: "PG-13",
    Released: "18 Jul 2008",
    Runtime: "152 min",
    Genre: "Action, Crime, Drama",
    Director: "Christopher Nolan",
    Writer: "Jonathan Nolan, Christopher Nolan, David S. Goyer",
    Actors: "Christian Bale, Heath Ledger, Aaron Eckhart",
    Plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    Language: "English, Mandarin",
    Country: "United States, United Kingdom",
    Awards: "Won 2 Oscars. 160 wins & 163 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "9.0/10" },
      { Source: "Rotten Tomatoes", Value: "94%" },
      { Source: "Metacritic", Value: "84/100" },
    ],
    Metascore: "84",
    imdbRating: "9.0",
    imdbVotes: "2,628,154",
    imdbID: "tt0468569",
    Type: "movie",
    DVD: "09 Dec 2008",
    BoxOffice: "$534,987,076",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Lord of the Rings: The Return of the King",
    Year: "2003",
    Rated: "PG-13",
    Released: "17 Dec 2003",
    Runtime: "201 min",
    Genre: "Action, Adventure, Drama",
    Director: "Peter Jackson",
    Writer: "J.R.R. Tolkien, Fran Walsh, Philippa Boyens",
    Actors: "Elijah Wood, Viggo Mortensen, Ian McKellen",
    Plot: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    Language: "English, Quenya, Old English, Sindarin",
    Country: "New Zealand, United States",
    Awards: "Won 11 Oscars. 209 wins & 124 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "9.0/10" },
      { Source: "Rotten Tomatoes", Value: "93%" },
      { Source: "Metacritic", Value: "94/100" },
    ],
    Metascore: "94",
    imdbRating: "9.0",
    imdbVotes: "1,830,463",
    imdbID: "tt0167260",
    Type: "movie",
    DVD: "25 May 2004",
    BoxOffice: "$378,251,207",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Schindler's List",
    Year: "1993",
    Rated: "R",
    Released: "04 Feb 1994",
    Runtime: "195 min",
    Genre: "Biography, Drama, History",
    Director: "Steven Spielberg",
    Writer: "Thomas Keneally, Steven Zaillian",
    Actors: "Liam Neeson, Ralph Fiennes, Ben Kingsley",
    Plot: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
    Language: "English, Hebrew, German, Polish, Latin",
    Country: "United States",
    Awards: "Won 7 Oscars. 91 wins & 49 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "9.0/10" },
      { Source: "Rotten Tomatoes", Value: "98%" },
      { Source: "Metacritic", Value: "94/100" },
    ],
    Metascore: "94",
    imdbRating: "9.0",
    imdbVotes: "1,345,151",
    imdbID: "tt0108052",
    Type: "movie",
    DVD: "12 Feb 2008",
    BoxOffice: "$96,898,818",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Godfather Part II",
    Year: "1974",
    Rated: "R",
    Released: "18 Dec 1974",
    Runtime: "202 min",
    Genre: "Crime, Drama",
    Director: "Francis Ford Coppola",
    Writer: "Francis Ford Coppola, Mario Puzo",
    Actors: "Al Pacino, Robert De Niro, Robert Duvall",
    Plot: "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
    Language: "English, Italian, Spanish, Latin, Sicilian",
    Country: "United States",
    Awards: "Won 6 Oscars. 17 wins & 20 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "9.0/10" },
      { Source: "Rotten Tomatoes", Value: "96%" },
      { Source: "Metacritic", Value: "90/100" },
    ],
    Metascore: "90",
    imdbRating: "9.0",
    imdbVotes: "1,260,911",
    imdbID: "tt0071562",
    Type: "movie",
    DVD: "24 May 2005",
    BoxOffice: "$47,834,595",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "12 Angry Men",
    Year: "1957",
    Rated: "Approved",
    Released: "10 Apr 1957",
    Runtime: "96 min",
    Genre: "Crime, Drama",
    Director: "Sidney Lumet",
    Writer: "Reginald Rose",
    Actors: "Henry Fonda, Lee J. Cobb, Martin Balsam",
    Plot: "The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.",
    Language: "English",
    Country: "United States",
    Awards: "Nominated for 3 Oscars. 17 wins & 13 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "9.0/10" },
      { Source: "Rotten Tomatoes", Value: "100%" },
      { Source: "Metacritic", Value: "96/100" },
    ],
    Metascore: "96",
    imdbRating: "9.0",
    imdbVotes: "782,913",
    imdbID: "tt0050083",
    Type: "movie",
    DVD: "04 Mar 2008",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Jai Bhim",
    Year: "2021",
    Rated: "TV-MA",
    Released: "02 Nov 2021",
    Runtime: "164 min",
    Genre: "Crime, Drama, Mystery",
    Director: "T.J. Gnanavel",
    Writer: "T.J. Gnanavel, Rajendra Sapre",
    Actors: "Suriya, Lijo Mol Jose, Manikandan K.",
    Plot: "When a tribal man is arrested for a case of alleged theft, his wife turns to a human-rights lawyer to help bring justice.",
    Language: "Tamil, Hindi, Telugu",
    Country: "India",
    Awards: "3 wins & 12 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOTM0NWFjNGYtNjExMS00ZTZlLWFiYmMtZmU4ZjZkMmMxZTNjXkEyXkFqcGdeQXVyODEyNjEwMDk@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.9/10" },
      { Source: "Rotten Tomatoes", Value: "100%" },
    ],
    Metascore: "N/A",
    imdbRating: "8.9",
    imdbVotes: "198,869",
    imdbID: "tt15097216",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Pulp Fiction",
    Year: "1994",
    Rated: "R",
    Released: "14 Oct 1994",
    Runtime: "154 min",
    Genre: "Crime, Drama",
    Director: "Quentin Tarantino",
    Writer: "Quentin Tarantino, Roger Avary",
    Actors: "John Travolta, Uma Thurman, Samuel L. Jackson",
    Plot: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    Language: "English, Spanish, French",
    Country: "United States",
    Awards: "Won 1 Oscar. 70 wins & 75 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.9/10" },
      { Source: "Rotten Tomatoes", Value: "92%" },
      { Source: "Metacritic", Value: "94/100" },
    ],
    Metascore: "94",
    imdbRating: "8.9",
    imdbVotes: "2,032,272",
    imdbID: "tt0110912",
    Type: "movie",
    DVD: "20 Aug 2002",
    BoxOffice: "$107,928,762",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Inception",
    Year: "2010",
    Rated: "PG-13",
    Released: "16 Jul 2010",
    Runtime: "148 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Christopher Nolan",
    Writer: "Christopher Nolan",
    Actors: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
    Plot: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
    Language: "English, Japanese, French",
    Country: "United States, United Kingdom",
    Awards: "Won 4 Oscars. 158 wins & 220 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.8/10" },
      { Source: "Rotten Tomatoes", Value: "87%" },
      { Source: "Metacritic", Value: "74/100" },
    ],
    Metascore: "74",
    imdbRating: "8.8",
    imdbVotes: "2,328,647",
    imdbID: "tt1375666",
    Type: "movie",
    DVD: "07 Dec 2010",
    BoxOffice: "$292,587,330",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
];
